version: '3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    volumes:
      - .:/var/www
    depends_on:
      - mysql

  mysql:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_DATABASE: "agenda"
      MYSQL_ROOT_PASSWORD: "password"
    volumes:
      - db-data:/var/lib/mysql
    ports:
      - 3303:3306

  web:
    container_name: web
    image: nginx:latest
    restart: always
    ports:
      - "8005:80"
    volumes:
      - .:/var/www
      - ./docker/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app

volumes:
  db-data: